### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by ibruxel** [microchip-pic-avr-solutions/encx24j600-tcpip-solution#1]
On update MAC duplex settings to match PHY duplex setting, when switch to half duplex the the code 
macon2Val |= MACON2_FULDPX_OFF;
I think it should be 
macon2Val &= MACON2_FULDPX_OFF?

because it will turn all bits to 1 instead of turn of bit 0 
https://github.com/microchip-pic-avr-solutions/encx24j600-tcpip-solution/blob/a5d9c181b72e9adda049219107ff91c4ae7303b0/encx24j600-tcp-client-solution.X/mcc_generated_files/TCPIPLibrary/ENCx24J600_driver.c#LL516C38-L516C38

**Comment by pic-avr-github-admin** [comment]
New Solution available - follow links from README
